# IMPORTANT NOTE
#
# Although our primary CI environment for tiktoken-grpc is GitHub Actions, we rely on CircleCI for docker building and
# pushing due to the easy availability of the arm based machine runners.
# DO NOT put workflows that are related to building docker images in here.
# Instead, put them in `.circleci/config.yml`.

name: lint-test-publish

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  warmpycache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: install poetry
        run: pipx install poetry

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: poetry install

  # Run linter against protobuf files
  buflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: bufbuild/buf-setup-action@00661b48f00bf682921f8aab99306c7f1a7a3ec3 # v1.15.1
        with:
          version: 1.15.1
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@bd48f53224baaaf0fc55de9a913e7680ca6dbea4 # v1.0.3

  # Run linter against python files
  lint:
    runs-on: ubuntu-latest
    needs: warmpycache
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: install poetry
        run: pipx install poetry

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: poetry install

      - run: poetry run poe lint

  # Run python tests
  test:
    runs-on: ubuntu-latest
    needs: warmpycache
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: install poetry
        run: pipx install poetry

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: poetry install

      - run: poetry run poe test
